import type { MarvinAsset, MarvinEntry, SiteClient } from "./types";

export const sampleAssets: MarvinAsset[] = [
  {
    id: "asset-foundry-workshop",
    slug: "foundry-jacket-workshop-display",
    name: "Foundry Jacket Workshop Display",
    url: "/placeholder.svg",
    mimeType: "image/svg+xml",
    altText: "Workshop table with denim, tools, and jacket details",
    width: 1200,
    height: 800,
    metadata: { tone: "foundry" },
    role: "featured",
    usage: "workshop",
    position: 0,
    focalPoint: "50% 50%",
  },
  {
    id: "asset-denim-detail",
    slug: "selvedge-denim-detail",
    name: "Selvedge Denim Detail",
    url: "/placeholder.svg",
    mimeType: "image/svg+xml",
    altText: "Close view of dark selvedge denim",
    width: 1200,
    height: 800,
    metadata: { tone: "denim" },
    role: "support",
    usage: "material",
    position: 1,
    focalPoint: "50% 50%",
  },
];

export const sampleEntries: MarvinEntry[] = [
  {
    id: "entry-foundry-jacket",
    slug: "foundry-jacket",
    title: "The Foundry Jacket",
    entry_type: "project",
    entryTypeId: "type-project",
    groupId: "group-main",
    summary: "Made one at a time in the workshop from 12oz Japanese selvedge denim.",
    status: "published",
    published_at: "2026-07-04T12:00:00Z",
    collections: ["projects", "current-work"],
    frontmatter: {
      schema: "mashburn.project.v1",
      projectNumber: "Project 006",
      category: "Jackets",
      material: "12oz Japanese Selvedge Denim",
      availability: "Available",
      workshopVerdict: "Probably Overbuilt.",
      leadTime: "2-3 Weeks",
      featured: true,
    },
    assets: sampleAssets,
  },
  {
    id: "entry-notes-on-selvedge",
    slug: "notes-on-selvedge",
    title: "Notes on Selvedge",
    entry_type: "bench_note",
    entryTypeId: "type-bench-note",
    groupId: "group-main",
    summary: "The sweet spot: tough enough to last, comfortable enough to live in.",
    status: "published",
    published_at: "2026-06-10T12:00:00Z",
    collections: ["bench-notes"],
    frontmatter: {
      schema: "mashburn.bench_note.v1",
      category: "Materials",
      noteNumber: "012",
      readTime: "5 min",
      tags: ["Making", "Materials"],
    },
    assets: [sampleAssets[1]],
  },
  {
    id: "entry-care-guide",
    slug: "care-guide",
    title: "Care Guide",
    entry_type: "reference",
    entryTypeId: "type-reference",
    groupId: "group-main",
    summary: "How to care for pieces built to wear in, not wear out.",
    status: "draft",
    collections: ["workshop-reference"],
    frontmatter: {
      schema: "mashburn.reference.v1",
      order: 5,
    },
    assets: [],
  },
];

export const sampleSiteClients: SiteClient[] = [
  {
    id: "client-mashburn",
    name: "Mash & Burn Co.",
    slug: "mashandburnco",
    is_active: true,
    permissions: ["read:published_entries", "read:collections", "read:assets"],
    last_used_at: "2026-07-04T13:20:00Z",
  },
];
