apiVersion: v2
name: marvin
description: Marvin event bus application with webhooks and scheduler
type: application
version: 1.2.0
appVersion: "2026.06.05"

keywords:
  - marvin
  - event-bus
  - webhooks
  - scheduler

maintainers:
  - name: Jared Mash
    email: engineering@inneropen.org

home: https://github.com/InnerOpen/marvin
sources:
  - https://github.com/InnerOpen/marvin

# Minimum Helm version required
kubeVersion: ">=1.19.0-0"
