apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marvin.fullname" . }}
  labels:
    {{- include "marvin.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtpHost: {{ .Values.secrets.smtpHost | quote }}
  smtpPort: {{ .Values.secrets.smtpPort | quote }}
  smtpUser: {{ .Values.secrets.smtpUser | default "" | quote }}
  smtpPassword: {{ .Values.secrets.smtpPassword | default "" | quote }}
  smtpFromEmail: {{ .Values.secrets.smtpFromEmail | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.apiKey }}
  apiKey: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
