apiVersion: v1
kind: Service
metadata:
  name: {{ include "marvin.fullname" . }}
  labels:
    {{- include "marvin.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.frontendPort }}
    targetPort: frontend
    protocol: TCP
    name: frontend
  selector:
    {{- include "marvin.selectorLabels" . | nindent 4 }}
