services:
    marvin:
        container_name: marvin
        image: marvin:dev
        build:
            context: ../
            target: production
            dockerfile: ./docker/Dockerfile
        restart: always
        volumes:
          - marvin-data:/app/data
        ports:
            - 8080:8080
        environment:
            PRODUCTION: True
            ALLOW_SIGNUP: "false"
            LOG_LEVEL: DEBUG
            DB_ENGINE: sqlite
        secrets:
          - DB_ENGINE
volumes:
  marvin-data:
    driver: local
secrets:
    DB_ENGINE:
        environment: COLORTERM
