# TODO: Auto-derive payload examples from EventDocumentDataBase subclasses
# via model_json_schema() or dummy-instance construction instead of this
# hand-maintained dict. See GitHub issue or tasks/todo.md.
"""
Maps event types to their real webhook payload structure.

Builds example payloads from the actual EventDocumentDataBase subclasses
so the Connect webhook page shows exactly what will be received.
"""

from marvin.core.root_logger import get_logger

logger = get_logger(__name__)

# Wrapper showing the full webhook payload structure
PAYLOAD_WRAPPER = {
    "eventType": "<event_type_name>",
    "eventId": "evt_a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "timestamp": "2026-07-16T00:00:00Z",
    "workspaceId": "<workspace-uuid>",
    "integrationId": "<integration-name>",
    "message": {
        "title": "<Event Label>",
        "body": "<event description>",
    },
    "documentData": {},  # replaced per event type
}


def get_payload_example(event_type: str) -> dict:
    """Build an example webhook payload for the given event type."""
    from marvin.services.event_bus_service.event_types import EventTypes

    # Map event type names to their document data classes and example values
    doc_data_map = {
        # --- Invitation events ---
        "invitation_sent": {
            "documentType": "invitation",
            "operation": "info",
            "invitationToken": "abc123token",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "inviterName": "Jane Smith",
            "inviteeEmail": "user@example.com",
            "invitationUrl": "https://yoursite.com/register?token=abc123",
            "usesLeft": 5,
        },
        "invitation_created": {
            "documentType": "invitation",
            "operation": "create",
            "invitationToken": "abc123token",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "inviterName": "Jane Smith",
            "usesLeft": 10,
        },
        "invitation_accepted": {
            "documentType": "invitation",
            "operation": "update",
            "invitationToken": "abc123token",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "inviteeEmail": "user@example.com",
        },
        # --- Workspace events ---
        "workspace_created": {
            "documentType": "generic",
            "operation": "create",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "creatorId": "<user-uuid>",
            "creatorName": "Jane Smith",
        },
        "workspace_updated": {
            "documentType": "workspace",
            "operation": "update",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "workspaceSlug": "my-workspace",
        },
        # --- Member events ---
        "member_added": {
            "documentType": "member",
            "operation": "create",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "userId": "<user-uuid>",
            "username": "jane.smith",
            "userFullName": "Jane Smith",
            "role": "EDITOR",
        },
        "member_role_changed": {
            "documentType": "member",
            "operation": "update",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "userId": "<user-uuid>",
            "username": "jane.smith",
            "userFullName": "Jane Smith",
            "role": "ADMIN",
            "previousRole": "EDITOR",
        },
        "member_removed": {
            "documentType": "member",
            "operation": "delete",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "userId": "<user-uuid>",
            "username": "jane.smith",
            "userFullName": "Jane Smith",
            "role": "EDITOR",
        },
        # --- Entry events ---
        "entry_created": {
            "documentType": "entry",
            "operation": "create",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_updated": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_published": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_unpublished": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_archived": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_restored": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_deleted": {
            "documentType": "entry",
            "operation": "delete",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_added_to_collection": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "entry_removed_from_collection": {
            "documentType": "entry",
            "operation": "update",
            "entryId": "<entry-uuid>",
            "entryTitle": "My Blog Post",
            "entryType": "post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        # --- Collection events ---
        "collection_created": {
            "documentType": "collection",
            "operation": "create",
            "collectionId": "<collection-uuid>",
            "collectionName": "Featured Posts",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "collection_updated": {
            "documentType": "collection",
            "operation": "update",
            "collectionId": "<collection-uuid>",
            "collectionName": "Featured Posts",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "collection_deleted": {
            "documentType": "collection",
            "operation": "delete",
            "collectionId": "<collection-uuid>",
            "collectionName": "Featured Posts",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        # --- Asset events ---
        "asset_uploaded": {
            "documentType": "asset",
            "operation": "create",
            "assetId": "<asset-uuid>",
            "name": "photo.jpg",
            "slug": "photo-jpg",
            "mimeType": "image/jpeg",
            "assetType": "image",
            "storageKey": "assets/photo.jpg",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "uploaderId": "<user-uuid>",
            "uploaderName": "Jane Smith",
        },
        "asset_updated": {
            "documentType": "asset",
            "operation": "update",
            "assetId": "<asset-uuid>",
            "name": "photo.jpg",
            "slug": "photo-jpg",
            "mimeType": "image/jpeg",
            "assetType": "image",
            "storageKey": "assets/photo.jpg",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "uploaderId": "<user-uuid>",
            "uploaderName": "Jane Smith",
        },
        "asset_deleted": {
            "documentType": "asset",
            "operation": "delete",
            "assetId": "<asset-uuid>",
            "name": "photo.jpg",
            "slug": "photo-jpg",
            "mimeType": "image/jpeg",
            "assetType": "image",
            "storageKey": "assets/photo.jpg",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "uploaderId": "<user-uuid>",
            "uploaderName": "Jane Smith",
        },
        # --- Form events ---
        "form_created": {
            "documentType": "form",
            "operation": "create",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "form_updated": {
            "documentType": "form",
            "operation": "update",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "form_published": {
            "documentType": "form",
            "operation": "update",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "form_archived": {
            "documentType": "form",
            "operation": "update",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "form_deleted": {
            "documentType": "form",
            "operation": "delete",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "authorId": "<user-uuid>",
            "authorName": "Jane Smith",
        },
        "form_submission_received": {
            "documentType": "form_submission",
            "operation": "create",
            "formId": "<form-uuid>",
            "formName": "Contact Form",
            "submissionId": "<submission-uuid>",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "submissionData": {"name": "John Doe", "message": "Hello!"},
        },
        # --- API client events ---
        "api_client_created": {
            "documentType": "api_client",
            "operation": "create",
            "apiClientId": "<api-client-uuid>",
            "apiClientName": "My Site Client",
            "apiClientSlug": "my-site-client",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "permissions": {"entries": True, "assets": True},
            "enabled": True,
            "createdByName": "Jane Smith",
        },
        "api_client_updated": {
            "documentType": "api_client",
            "operation": "update",
            "apiClientId": "<api-client-uuid>",
            "apiClientName": "My Site Client",
            "apiClientSlug": "my-site-client",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "permissions": {"entries": True, "assets": True},
            "enabled": True,
            "createdByName": "Jane Smith",
        },
        "api_client_deleted": {
            "documentType": "api_client",
            "operation": "delete",
            "apiClientId": "<api-client-uuid>",
            "apiClientName": "My Site Client",
            "apiClientSlug": "my-site-client",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "permissions": {"entries": True, "assets": True},
            "enabled": True,
            "createdByName": "Jane Smith",
        },
        # --- Resource events ---
        "resource_created": {
            "documentType": "resource",
            "operation": "create",
            "resourceId": "<resource-uuid>",
            "resourceName": "Acme Supplier",
            "resourceSlug": "acme-supplier",
            "resourceType": "supplier",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "resource_updated": {
            "documentType": "resource",
            "operation": "update",
            "resourceId": "<resource-uuid>",
            "resourceName": "Acme Supplier",
            "resourceSlug": "acme-supplier",
            "resourceType": "supplier",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "resource_deleted": {
            "documentType": "resource",
            "operation": "delete",
            "resourceId": "<resource-uuid>",
            "resourceName": "Acme Supplier",
            "resourceSlug": "acme-supplier",
            "resourceType": "supplier",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        # --- Entry type events ---
        "entry_type_created": {
            "documentType": "entry_type",
            "operation": "create",
            "entryTypeId": "<entry-type-uuid>",
            "entryTypeName": "Blog Post",
            "entryTypeSlug": "blog-post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "entry_type_updated": {
            "documentType": "entry_type",
            "operation": "update",
            "entryTypeId": "<entry-type-uuid>",
            "entryTypeName": "Blog Post",
            "entryTypeSlug": "blog-post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        "entry_type_deleted": {
            "documentType": "entry_type",
            "operation": "delete",
            "entryTypeId": "<entry-type-uuid>",
            "entryTypeName": "Blog Post",
            "entryTypeSlug": "blog-post",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
        },
        # --- Scheduled task events ---
        "scheduled_task_created": {
            "documentType": "generic",
            "operation": "info",
            "taskId": "<task-uuid>",
            "taskName": "Daily Cleanup",
            "taskSlug": "daily-cleanup",
            "taskType": "cleanup_temp_files",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "enabled": True,
        },
        "scheduled_task_updated": {
            "documentType": "generic",
            "operation": "info",
            "taskId": "<task-uuid>",
            "taskName": "Daily Cleanup",
            "taskSlug": "daily-cleanup",
            "taskType": "cleanup_temp_files",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "enabled": True,
        },
        "scheduled_task_deleted": {
            "documentType": "generic",
            "operation": "info",
            "taskId": "<task-uuid>",
            "taskName": "Daily Cleanup",
            "taskSlug": "daily-cleanup",
            "taskType": "cleanup_temp_files",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "enabled": True,
        },
        "scheduled_task_completed": {
            "documentType": "generic",
            "operation": "info",
            "taskId": "<task-uuid>",
            "taskName": "Daily Cleanup",
            "taskSlug": "daily-cleanup",
            "taskType": "cleanup_temp_files",
            "workspaceId": "<workspace-uuid>",
            "workspaceName": "My Workspace",
            "enabled": True,
            "lastStatus": "completed",
        },
    }

    doc_data = doc_data_map.get(event_type, {
        "documentType": "generic",
        "operation": "info",
        "workspaceId": "<workspace-uuid>",
    })

    # Find label from EventTypes if possible
    try:
        et = EventTypes[event_type]
        label = event_type.replace("_", " ").title()
    except KeyError:
        label = event_type.replace("_", " ").title()

    return {
        "eventType": event_type,
        "eventId": "851a54f3-bc85-4123-aa35-7c139db2cb59",
        "timestamp": "2026-07-16T00:34:37Z",
        "workspaceId": "<workspace-uuid>",
        "integrationId": "marvin_integration",
        "message": {
            "title": label,
            "body": f"Event: {event_type}",
        },
        "documentData": doc_data,
    }
