"""add asset_tags and resource_tags tables

Extends the shared tag vocabulary to assets and resources (Phase 2), mirroring entry_tags.
Schema was autogenerated; the indexes are hand-added (autogenerate misses the `index=True`
columns, same as the entry_tags migration).

Revision ID: b7e4430df8eb
Revises: 8f943c27be3b
Create Date: 2026-07-20 14:25:40.825202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'b7e4430df8eb'
down_revision: Union[str, None] = '8f943c27be3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('asset_tags',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('asset_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('tag_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('created_at', marvin.db.migration_types.NaiveDateTime(), nullable=True),
    sa.Column('update_at', marvin.db.migration_types.NaiveDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'tag_id')
    )
    op.create_index('ix_asset_tags_asset_id', 'asset_tags', ['asset_id'])
    op.create_index('ix_asset_tags_tag_id', 'asset_tags', ['tag_id'])
    op.create_table('resource_tags',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('resource_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('tag_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('created_at', marvin.db.migration_types.NaiveDateTime(), nullable=True),
    sa.Column('update_at', marvin.db.migration_types.NaiveDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'tag_id')
    )
    op.create_index('ix_resource_tags_resource_id', 'resource_tags', ['resource_id'])
    op.create_index('ix_resource_tags_tag_id', 'resource_tags', ['tag_id'])


def downgrade() -> None:
    op.drop_index('ix_resource_tags_tag_id', table_name='resource_tags')
    op.drop_index('ix_resource_tags_resource_id', table_name='resource_tags')
    op.drop_table('resource_tags')
    op.drop_index('ix_asset_tags_tag_id', table_name='asset_tags')
    op.drop_index('ix_asset_tags_asset_id', table_name='asset_tags')
    op.drop_table('asset_tags')
