"""add resources and assets tables

Revision ID: ba8612ae5c08
Revises: f88932c8b808
Create Date: 2026-07-05 03:19:33.394872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'ba8612ae5c08'
down_revision: Union[str, None] = 'f88932c8b808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create resources table
    op.create_table('resources',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('group_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug')
    )
    op.create_index(op.f('ix_resources_group_id'), 'resources', ['group_id'], unique=False)

    # Create assets table
    op.create_table('assets',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('group_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug')
    )
    op.create_index(op.f('ix_assets_group_id'), 'assets', ['group_id'], unique=False)

    # Create entry_resources junction table
    op.create_table('entry_resources',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('entry_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('resource_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'resource_id')
    )
    op.create_index(op.f('ix_entry_resources_entry_id'), 'entry_resources', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_resources_resource_id'), 'entry_resources', ['resource_id'], unique=False)
    op.create_index('ix_entry_resources_entry_id_position', 'entry_resources', ['entry_id', 'position'], unique=False)

    # Create entry_assets junction table
    op.create_table('entry_assets',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('entry_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('asset_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('focal_point', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'asset_id')
    )
    op.create_index(op.f('ix_entry_assets_entry_id'), 'entry_assets', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_assets_asset_id'), 'entry_assets', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_assets_asset_id'), table_name='entry_assets')
    op.drop_index(op.f('ix_entry_assets_entry_id'), table_name='entry_assets')
    op.drop_table('entry_assets')
    op.drop_index('ix_entry_resources_entry_id_position', table_name='entry_resources')
    op.drop_index(op.f('ix_entry_resources_resource_id'), table_name='entry_resources')
    op.drop_index(op.f('ix_entry_resources_entry_id'), table_name='entry_resources')
    op.drop_table('entry_resources')
    op.drop_index(op.f('ix_assets_group_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_resources_group_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
