"""add scheduler leadership lock

Revision ID: 8a73900e8fe4
Revises: 3d7141617368
Create Date: 2026-07-24 16:24:24.497263

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = "8a73900e8fe4"
down_revision: str | None = "3d7141617368"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduler_lock",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("holder_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduler_lock", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scheduler_lock_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduler_lock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduler_lock_created_at"))

    op.drop_table("scheduler_lock")
    # ### end Alembic commands ###
