"""add suggestion_json to assets and resources

Lets AI write-back stage suggestions on assets/resources, mirroring entries.suggestion_json.

Revision ID: e4828972bdca
Revises: 930f9ab5902d
Create Date: 2026-07-20 15:05:41.712946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'e4828972bdca'
down_revision: Union[str, None] = '930f9ab5902d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('suggestion_json')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('suggestion_json')

    # ### end Alembic commands ###
