"""add default_register to workspace_ai_settings

Revision ID: e01c3719b3e6
Revises: 22fc8d0a41bb
Create Date: 2026-07-20 12:26:55.452786

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e01c3719b3e6"
down_revision: str | None = "22fc8d0a41bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_ai_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_register", sa.String(), server_default="auto", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_ai_settings", schema=None) as batch_op:
        batch_op.drop_column("default_register")

    # ### end Alembic commands ###
