"""add site_clients table

Revision ID: b39de631a423
Revises: ed9becc53b7f
Create Date: 2026-07-05 00:43:16.069812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'b39de631a423'
down_revision: Union[str, None] = 'ed9becc53b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_clients',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('group_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug')
    )
    op.create_index(op.f('ix_site_clients_group_id'), 'site_clients', ['group_id'], unique=False)
    op.create_index(op.f('ix_site_clients_token_hash'), 'site_clients', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_urls', schema=None) as batch_op:
        batch_op.alter_column('webhook_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.Enum('GET', 'POST', name='method'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'POST'"))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('group_events_notifier_options', schema=None) as batch_op:
        batch_op.alter_column('group_event_notifiers_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    op.drop_table('site_clients')
    op.drop_table('report_entries')
    # ### end Alembic commands ###
