"""add collection asset/resource junctions and target_type

Lets a smart collection target assets or resources (target_type) and materialize membership into
collection_assets / collection_resources. Indexes are hand-added (autogenerate misses index=True).

Revision ID: ae76953cdc37
Revises: e4828972bdca
Create Date: 2026-07-20 15:51:21.994916

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = "ae76953cdc37"
down_revision: str | None = "e4828972bdca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_assets",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("collection_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("asset_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "asset_id"),
    )
    op.create_index("ix_collection_assets_collection_id", "collection_assets", ["collection_id"])
    op.create_index("ix_collection_assets_asset_id", "collection_assets", ["asset_id"])
    op.create_table(
        "collection_resources",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("collection_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("resource_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "resource_id"),
    )
    op.create_index("ix_collection_resources_collection_id", "collection_resources", ["collection_id"])
    op.create_index("ix_collection_resources_resource_id", "collection_resources", ["resource_id"])
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("target_type", sa.String(), server_default="entry", nullable=False))


def downgrade() -> None:
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("target_type")

    op.drop_index("ix_collection_resources_resource_id", table_name="collection_resources")
    op.drop_index("ix_collection_resources_collection_id", table_name="collection_resources")
    op.drop_table("collection_resources")
    op.drop_index("ix_collection_assets_asset_id", table_name="collection_assets")
    op.drop_index("ix_collection_assets_collection_id", table_name="collection_assets")
    op.drop_table("collection_assets")
