"""add collections tables

Revision ID: ed9becc53b7f
Revises: 0b49e79f3a1f
Create Date: 2026-07-05 00:07:49.155026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'ed9becc53b7f'
down_revision: Union[str, None] = '0b49e79f3a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('group_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('smart_rules', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug')
    )
    op.create_index(op.f('ix_collections_group_id'), 'collections', ['group_id'], unique=False)
    op.create_table('entry_collections',
    sa.Column('id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('entry_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('collection_id', marvin.db.migration_types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'collection_id')
    )
    op.create_index(op.f('ix_entry_collections_entry_id'), 'entry_collections', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_collections_collection_id'), 'entry_collections', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_collections_collection_id'), table_name='entry_collections')
    op.drop_index(op.f('ix_entry_collections_entry_id'), table_name='entry_collections')
    op.drop_table('entry_collections')
    op.drop_index(op.f('ix_collections_group_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
