"""initial schema

Revision ID: d1d2bc0fed86
Revises:
Create Date: 2026-07-07 21:17:30.239585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types
from sqlalchemy.dialects.postgresql import ARRAY


# Determine if we're using PostgreSQL
def is_postgresql():
    """Check if the database is PostgreSQL."""
    return op.get_bind().dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision: str = "d1d2bc0fed86"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    use_pg = is_postgresql()
    array_type = ARRAY(sa.String()) if use_pg else sa.Text()  # Store as JSON text in SQLite

    op.create_table(
        "events_notifier_options",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "groups",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collections",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("is_smart", sa.Boolean(), nullable=False),
        sa.Column("smart_rules", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
    )
    op.create_table(
        "entry_types",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("schema_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("data_json", sa.JSON(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
    )
    op.create_table(
        "group_events_notifiers",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("apprise_url", sa.String(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create event_log table
    op.create_table(
        "event_log",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("event_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("entity_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("integration_id", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("message_title", sa.String(), nullable=False),
        sa.Column("message_body", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("update_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["workspace_id"], ["groups.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )
    # Create indexes for event_log
    op.create_index("ix_event_log_event_id", "event_log", ["event_id"], unique=True)
    op.create_index("ix_event_log_event_type", "event_log", ["event_type"])
    op.create_index("ix_event_log_occurred_at", "event_log", ["occurred_at"])
    op.create_index("ix_event_log_workspace_id", "event_log", ["workspace_id"])
    op.create_index("ix_event_log_user_id", "event_log", ["user_id"])
    op.create_index("ix_event_log_entity_id", "event_log", ["entity_id"])
    op.create_index("ix_event_log_entity_type", "event_log", ["entity_type"])
    op.create_index(
        "ix_event_log_workspace_type_time",
        "event_log",
        ["workspace_id", "event_type", "occurred_at"],
    )
    op.create_index("ix_event_log_user_time", "event_log", ["user_id", "occurred_at"])
    op.create_index(
        "ix_event_log_entity",
        "event_log",
        ["entity_id", "entity_type", "occurred_at"],
    )
    op.create_table(
        "group_preferences",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("private_group", sa.Boolean(), nullable=True),
        sa.Column("first_day_of_week", sa.Integer(), nullable=True),
        sa.Column("site_title", sa.String(), nullable=True),
        sa.Column("site_tagline", sa.String(), nullable=True),
        sa.Column("site_description", sa.String(), nullable=True),
        sa.Column("site_canonical_url", sa.String(), nullable=True),
        sa.Column("site_logo", sa.String(), nullable=True),
        sa.Column("site_favicon", sa.String(), nullable=True),
        sa.Column("site_locale", sa.String(), nullable=True),
        sa.Column("site_timezone", sa.String(), nullable=True),
        sa.Column("site_contact_email", sa.String(), nullable=True),
        sa.Column("site_social_json", sa.JSON(), nullable=True),
        sa.Column("site_metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_reports",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("timestamp", marvin.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invite_tokens",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("uses_left", sa.Integer(), nullable=False),
        sa.Column("workspace_role", sa.String(), nullable=False, server_default="EDITOR"),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("workspace_role IN ('OWNER', 'ADMIN', 'EDITOR', 'AUTHOR', 'VIEWER')", name="ck_invite_tokens_workspace_role"),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("auth_method", sa.Enum("MARVIN", "LDAP", "OIDC", name="authmethod"), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("platform_role", sa.Enum("NONE", "SUPER_ADMIN", name="platformrole"), nullable=False),
        sa.Column("advanced", sa.Boolean(), nullable=True),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("active_group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("cache_key", sa.String(), nullable=True),
        sa.Column("login_attemps", sa.Integer(), nullable=True),
        sa.Column("locked_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("can_manage", sa.Boolean(), nullable=True),
        sa.Column("can_invite", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["active_group_id"], ["groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhook_urls",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", marvin.db.migration_types.HttpUrlType(), nullable=False),
        sa.Column("method", sa.Enum("GET", "POST", name="method"), nullable=False),
        sa.Column(
            "webhook_type",
            sa.Enum(
                "generic",
                "user",
                "workspace",
                "entry",
                "collection",
                "asset",
                "webhook",
                "member",
                "invitation",
                "api_token",
                "deployment",
                name="eventdocumenttype",
            ),
            nullable=True,
        ),
        sa.Column("subscribed_events", array_type, nullable=True),
        sa.Column("scheduled_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_clients",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
    )
    op.create_table(
        "assets",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("orientation", sa.Integer(), nullable=True),
        sa.Column("storage_provider", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("public_url", sa.String(), nullable=True),
        sa.Column("alt_text", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("uploaded_by", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "entries",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("entry_type_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("status", sa.String(), server_default="inbox", nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_by", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["entry_type_id"], ["entry_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
    )
    op.create_table(
        "group_events_notifier_options",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("group_event_notifiers_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_event_notifiers_id"],
            ["group_events_notifiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "long_live_tokens",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("revoked_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("user_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_by", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_entries",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("exception", sa.String(), nullable=True),
        sa.Column("timestamp", marvin.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("report_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["group_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_by", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "slug"),
    )
    op.create_table(
        "webhook_execution_logs",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("webhook_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_attempt", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhook_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("workspace_role", sa.Enum("OWNER", "ADMIN", "EDITOR", "AUTHOR", "VIEWER", name="workspacerole"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "group_id", name="uq_workspace_member"),
    )
    op.create_table(
        "entry_assets",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("entry_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("asset_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("usage", sa.String(), nullable=True),
        sa.Column("focal_point", sa.String(), nullable=True),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "asset_id"),
    )
    op.create_table(
        "entry_collections",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("entry_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("collection_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "collection_id"),
    )
    op.create_table(
        "entry_resources",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("entry_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("resource_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("quantity", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "resource_id"),
    )
    # Create scheduled_tasks table
    op.create_table(
        "scheduled_tasks",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("schedule_type", sa.String(), nullable=False),
        sa.Column("schedule_config", sa.JSON(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(), nullable=True),
        sa.Column("last_duration_ms", sa.Integer(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("task_config", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("retry_policy", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("update_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("group_id", "slug", name="uq_scheduled_tasks_group_slug"),
    )

    # Create indexes for scheduled_tasks
    op.create_index("ix_scheduled_tasks_group_id", "scheduled_tasks", ["group_id"])
    op.create_index("ix_scheduled_tasks_next_run_at", "scheduled_tasks", ["next_run_at"])
    op.create_index("ix_scheduled_tasks_task_type", "scheduled_tasks", ["task_type"])
    op.create_index("ix_scheduled_tasks_next_run", "scheduled_tasks", ["next_run_at", "enabled"])
    op.create_index("ix_scheduled_tasks_workspace", "scheduled_tasks", ["group_id", "enabled"])

    # Create scheduled_task_execution_log table
    op.create_table(
        "scheduled_task_execution_log",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("task_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", marvin.db.migration_types.GUID(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("retry_attempt", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["task_id"], ["scheduled_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
    )

    # Create indexes for scheduled_task_execution_log
    op.create_index("ix_task_execution_log_task_id", "scheduled_task_execution_log", ["task_id"])
    op.create_index("ix_task_execution_log_group_id", "scheduled_task_execution_log", ["group_id"])
    op.create_index("ix_task_execution_log_executed_at", "scheduled_task_execution_log", ["executed_at"])
    op.create_index("ix_task_execution_task_time", "scheduled_task_execution_log", ["task_id", "executed_at"])
    op.create_index("ix_task_execution_workspace_time", "scheduled_task_execution_log", ["group_id", "executed_at"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_resources")
    op.drop_table("entry_collections")
    op.drop_table("entry_assets")
    op.drop_table("workspace_members")
    op.drop_table("webhook_execution_logs")
    op.drop_table("resources")
    op.drop_table("report_entries")
    op.drop_table("password_reset_tokens")
    op.drop_table("long_live_tokens")
    op.drop_table("group_events_notifier_options")
    op.drop_table("entries")
    op.drop_table("assets")
    op.drop_table("api_clients")
    op.drop_table("webhook_urls")
    op.drop_table("users")
    op.drop_table("invite_tokens")
    op.drop_table("group_reports")
    op.drop_table("group_preferences")
    op.drop_table("group_events_notifiers")
    op.drop_table("entry_types")
    op.drop_table("collections")
    op.drop_table("groups")
    op.drop_table("events_notifier_options")

    # Drop all indexes first
    op.drop_index("ix_event_log_entity", table_name="event_log")
    op.drop_index("ix_event_log_user_time", table_name="event_log")
    op.drop_index("ix_event_log_workspace_type_time", table_name="event_log")
    op.drop_index("ix_event_log_entity_type", table_name="event_log")
    op.drop_index("ix_event_log_entity_id", table_name="event_log")
    op.drop_index("ix_event_log_user_id", table_name="event_log")
    op.drop_index("ix_event_log_workspace_id", table_name="event_log")
    op.drop_index("ix_event_log_occurred_at", table_name="event_log")
    op.drop_index("ix_event_log_event_type", table_name="event_log")
    op.drop_index("ix_event_log_event_id", table_name="event_log")

    # Drop the event_log table
    op.drop_table("event_log")

    # Drop indexes for scheduled_task_execution_log
    op.drop_index("ix_task_execution_workspace_time", table_name="scheduled_task_execution_log")
    op.drop_index("ix_task_execution_task_time", table_name="scheduled_task_execution_log")
    op.drop_index("ix_task_execution_log_executed_at", table_name="scheduled_task_execution_log")
    op.drop_index("ix_task_execution_log_group_id", table_name="scheduled_task_execution_log")
    op.drop_index("ix_task_execution_log_task_id", table_name="scheduled_task_execution_log")

    # Drop scheduled_task_execution_log table
    op.drop_table("scheduled_task_execution_log")

    # Drop indexes for scheduled_tasks
    op.drop_index("ix_scheduled_tasks_workspace", table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_next_run", table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_task_type", table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_next_run_at", table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_group_id", table_name="scheduled_tasks")

    # Drop scheduled_tasks table
    op.drop_table("scheduled_tasks")

    # ### end Alembic commands ###
